Starting event feature

diff --git a/miniplan/plan b/miniplan/plan
--- a/miniplan/plan
+++ b/miniplan/plan
@@ -48,7 +48,11 @@ completedList() {
 
 databasePath="${HOME}/.lowbit-planner"
 databaseTables="
+  completed
+  events
+  habits
   inbox
+  task
 "
 
 databaseCheckIfExists() {
@@ -305,6 +309,144 @@ doStart() {
 }
 
 #########
+# Event #
+#########
+
+eventAdd() {
+
+  logPrint debug "Event Add"
+
+  if [ "${3}" ]; then
+    thisEventDate="${1}"  ; logPrint debug "${thisEventDate}" ; shift
+    thisEventTime="${1}"  ; logPrint debug "${thisEventTime}" ; shift
+    thisEventName="${@}"  ; logPrint debug "${thisEventName}"
+  else
+    logPrint error "Missing one of required arguments"
+    exit 1
+  fi
+
+  if databaseTableCheckEntryExists event "|${thisEventName}$" ; then
+    logPrint error "Event already exists: '${thisEventName}'"
+    exit 1
+  fi
+
+  if databaseTableInsert event "[E]" "${thisEventDate} ${thisEventTime}" "${thisEventName}" ; then
+    logPrint info "New event created: '${thisEventName}'"
+  else
+    logPrint error "Failed to create event: '${thisEventName}'"
+  fi
+
+}
+
+eventComplete() {
+
+  if [ ! "${1}" ]; then
+    logPrint error "Missing task name"
+    exit 1
+  fi
+
+  thisTaskName="${@}"
+
+  if ! databaseTableCheckEntryExists task "|${thisTaskName}$" ; then
+    logPrint error "Task not found: '${thisTaskName}'"
+    exit 1
+  fi
+  
+  if ! databaseTableInsert completed "[X]" "`timestampGetNow`" "${thisTaskName}" ; then
+    logPrint error "Failed to mark task as completed: '${thisTaskName}'"
+    exit 1
+  fi
+
+  if ! databaseTableDeleteByString task "|${thisTaskName}$" ; then
+    logPrint error "Failed to delete task after marking it as completed: '${thisTaskName}'"
+    exit 1
+  fi
+
+  logPrint info "Yay! Another task completed: '${thisTaskName}'"
+
+}
+
+
+eventDelete() {
+
+  if [ ! "${1}" ]; then
+    logPrint error "Missing task name"
+    exit 1
+  fi
+
+  thisTaskName="${@}"
+
+  if ! databaseTableCheckEntryExists task "|${thisTaskName}$" ; then
+    logPrint error "Task not found: '${thisTaskName}'"
+    exit 1
+  fi
+  
+  if databaseTableDeleteByString task "|${thisTaskName}$" ; then
+    logPrint info "Task deleted: '${thisTaskName}'"
+  else
+    logPrint error "Failed to delete task: '${thisTaskName}'"
+  fi
+
+}
+
+eventList() {
+
+  logPrint debug "Task List"
+
+  databaseTableList task 10 asc 1 4
+
+}
+
+eventShowUsage() {
+
+  echo -e "${colorBold}Lowbit Planner - Task${colorReset}"
+  echo
+  echo -e "${colorBold}${colorLightGreen}Usage:${colorReset}"
+  echo -e "  ${colorBold}`basename $0` task${colorReset} ${colorUnderline}${colorLightRed}action${colorReset}${colorDim} [${colorReset}${colorUnderline}arguments${colorReset}${colorDim}]${colorReset}"
+  echo
+  echo -e "${colorBold}${colorLightGreen}Actions:${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}add${colorReset} ${colorUnderline}task_name${colorReset}            ${colorDim}- Create a new task${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}complete${colorReset} ${colorUnderline}task_name${colorReset}       ${colorDim}- Complete a task${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}delete${colorReset} ${colorUnderline}task_name${colorReset}         ${colorDim}- Delete a task${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}list${colorReset}                     ${colorDim}- List tasks${colorReset}"
+  echo
+  exit 0
+
+}
+
+eventRouter() {
+
+  if [ $1 ]; then
+    usrAction=$1  ; shift ; logPrint debug "Action => ${usrAction}"
+  else
+    eventShowUsage
+  fi
+
+  case ${usrAction} in
+    "add")
+      eventAdd "${@}"
+      ;;
+    "complete")
+      eventComplete "${@}"
+      ;;
+    "delete")
+      eventDelete "${@}"
+      ;;
+    "list")
+      eventList
+      ;;
+    "--help"|"-h"|"help")
+      eventShowUsage
+      ;;
+    *)
+      logPrint error "Unknown action '${usrAction}'"
+      ;;
+  esac
+
+}
+
+
+#########
 # Habit #
 #########
 
@@ -319,12 +461,20 @@ habitList() {
 
 helpShow() {
 
-  echo -e "${colorBold}${colorLightGreen}Item Status:${colorReset}"
-  echo -e "  ${colorBold}[ ]${colorReset} ${colorDim}- New Item${colorReset}"
-  echo -e "  ${colorBold}[>]${colorReset} ${colorDim}- Later${colorReset}"
-  echo -e "  ${colorBold}[H]${colorReset} ${colorDim}- Habit${colorReset}"
-  echo -e "  ${colorBold}[P]${colorReset} ${colorDim}- Part of a project${colorReset}"
-  echo -e "  ${colorBold}[X]${colorReset} ${colorDim}- Done${colorReset}"
+  echo "Help Topics:"
+  echo "- Inbox"
+  echo "- Tasks"
+  echo "- Habits"
+  echo "- Events"
+  echo "- Quick Commands"
+  echo "- Legend"
+  echo "- Commands Usage"
+  echo "- Search"
+  echo "- Completed Items"
+  echo "- Interactive Modes"
+  echo "- Link"
+  echo "- Update"
+  echo "- Sync"
 
 }
 
@@ -386,23 +536,7 @@ inboxList() {
 
 }
 
-inboxShowUsage() {
-
-  echo -e "${colorBold}Lowbit Planner - Inbox${colorReset}"
-  echo
-  echo -e "${colorBold}${colorLightGreen}Usage:${colorReset}"
-  echo -e "  ${colorBold}`basename $0` inbox${colorReset} ${colorUnderline}${colorLightRed}action${colorReset}${colorDim} [${colorReset}${colorUnderline}arguments${colorReset}${colorDim}]${colorReset}"
-  echo
-  echo -e "${colorBold}${colorLightGreen}Actions:${colorReset}"
-  echo -e "  ${colorUnderline}${colorLightRed}add${colorReset} ${colorUnderline}item_name${colorReset}    ${colorDim}- Add an item to the inbox${colorReset}"
-  echo -e "  ${colorUnderline}${colorLightRed}delete${colorReset} ${colorUnderline}item_name${colorReset} ${colorDim}- Delete an item from the inbox${colorReset}"
-  echo -e "  ${colorUnderline}${colorLightRed}list${colorReset}             ${colorDim}- List inbox items${colorReset}"
-  echo
-  exit 0
-
-}
-
-inboxParse() {
+inboxRouter() {
 
   if [ ! $1 ]; then
     inboxShowUsage
@@ -434,6 +568,22 @@ inboxParse() {
       logPrint error "Unknown action '${usrAction}'"
       ;;
   esac
+
+}
+
+inboxShowUsage() {
+
+  echo -e "${colorBold}Lowbit Planner - Inbox${colorReset}"
+  echo
+  echo -e "${colorBold}${colorLightGreen}Usage:${colorReset}"
+  echo -e "  ${colorBold}`basename $0` inbox${colorReset} ${colorUnderline}${colorLightRed}action${colorReset}${colorDim} [${colorReset}${colorUnderline}arguments${colorReset}${colorDim}]${colorReset}"
+  echo
+  echo -e "${colorBold}${colorLightGreen}Actions:${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}add${colorReset} ${colorUnderline}item_name${colorReset}    ${colorDim}- Add an item to the inbox${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}delete${colorReset} ${colorUnderline}item_name${colorReset} ${colorDim}- Delete an item from the inbox${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}list${colorReset}             ${colorDim}- List inbox items${colorReset}"
+  echo
+  exit 0
 
 }
 
@@ -727,7 +877,7 @@ syntaxShow() {
   # echo
   echo -e "${colorBold}${colorLightGreen}Basic commands:${colorReset}"
   echo -e "  ${colorUnderline}${colorLightMagenta}completed${colorReset}     ${colorDim}- List of completed items${colorReset}"
-  # echo -e "  ${colorUnderline}${colorLightMagenta}event${colorReset}         ${colorDim}- Event operations${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightMagenta}event${colorReset}         ${colorDim}- Event operations${colorReset}"
   # echo -e "  ${colorUnderline}${colorLightMagenta}habit${colorReset}         ${colorDim}- Habit operations${colorReset}"
   echo -e "  ${colorUnderline}${colorLightMagenta}inbox${colorReset}         ${colorDim}- Inbox operations${colorReset}"
   # echo -e "  ${colorUnderline}${colorLightMagenta}list${colorReset}          ${colorDim}- List of next items${colorReset}"
@@ -797,7 +947,7 @@ taskComplete() {
   fi
 
   if ! databaseTableDeleteByString task "|${thisTaskName}$" ; then
-    logPring error "Failed to delete task after marking it as completed: '${thisTaskName}'"
+    logPrint error "Failed to delete task after marking it as completed: '${thisTaskName}'"
     exit 1
   fi
 
@@ -823,7 +973,7 @@ taskDelete() {
   if databaseTableDeleteByString task "|${thisTaskName}$" ; then
     logPrint info "Task deleted: '${thisTaskName}'"
   else
-    logPring error "Failed to delete task: '${thisTaskName}'"
+    logPrint error "Failed to delete task: '${thisTaskName}'"
   fi
 
 }
@@ -836,7 +986,24 @@ taskList() {
 
 }
 
-taskParse() {
+taskShowUsage() {
+
+  echo -e "${colorBold}Lowbit Planner - Task${colorReset}"
+  echo
+  echo -e "${colorBold}${colorLightGreen}Usage:${colorReset}"
+  echo -e "  ${colorBold}`basename $0` task${colorReset} ${colorUnderline}${colorLightRed}action${colorReset}${colorDim} [${colorReset}${colorUnderline}arguments${colorReset}${colorDim}]${colorReset}"
+  echo
+  echo -e "${colorBold}${colorLightGreen}Actions:${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}add${colorReset} ${colorUnderline}task_name${colorReset}            ${colorDim}- Create a new task${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}complete${colorReset} ${colorUnderline}task_name${colorReset}       ${colorDim}- Complete a task${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}delete${colorReset} ${colorUnderline}task_name${colorReset}         ${colorDim}- Delete a task${colorReset}"
+  echo -e "  ${colorUnderline}${colorLightRed}list${colorReset}                     ${colorDim}- List tasks${colorReset}"
+  echo
+  exit 0
+
+}
+
+taskRouter() {
 
   if [ ! $1 ]; then
     taskShowUsage
@@ -876,72 +1043,46 @@ taskParse() {
 
 }
 
-taskShowUsage() {
-
-  echo -e "${colorBold}Lowbit Planner - Task${colorReset}"
-  echo
-  echo -e "${colorBold}${colorLightGreen}Usage:${colorReset}"
-  echo -e "  ${colorBold}`basename $0` task${colorReset} ${colorUnderline}${colorLightRed}action${colorReset}${colorDim} [${colorReset}${colorUnderline}arguments${colorReset}${colorDim}]${colorReset}"
-  echo
-  echo -e "${colorBold}${colorLightGreen}Actions:${colorReset}"
-  echo -e "  ${colorUnderline}${colorLightRed}add${colorReset} ${colorUnderline}task_name${colorReset}            ${colorDim}- Create a new task${colorReset}"
-  echo -e "  ${colorUnderline}${colorLightRed}complete${colorReset} ${colorUnderline}task_name${colorReset}       ${colorDim}- Complete a task${colorReset}"
-  echo -e "  ${colorUnderline}${colorLightRed}delete${colorReset} ${colorUnderline}task_name${colorReset}         ${colorDim}- Delete a task${colorReset}"
-  echo -e "  ${colorUnderline}${colorLightRed}list${colorReset}                     ${colorDim}- List tasks${colorReset}"
-  echo
-  exit 0
-
-}
-
 #############
 # Timestamp #
 #############
 
 timestampGetNow() {
-  date "+%Y-%m-%d %H:%M:%S"
+  date "+%Y-%m-%d %H:%M"
 }
 
 ################################################################################
 
-##########
-# Script #
-##########
-
-if [ ! $1 ]; then
+if [ $1 ]; then
+  usrCommand=$1 ; shift ; logPrint debug "Command => ${usrCommand}"
+else
   syntaxShow
 fi
-
-usrCommand=$1
 
 case ${usrCommand} in
 
   "add")
-    logPrint debug "Command => ${usrCommand}"
     databaseCheckIfExists
-    shift ; inboxAdd "${@}"
+    inboxAdd "${@}"
     ;;
   "completed")
     databaseCheckIfExists
-    logPrint debug "Command => ${usrCommand}"
     completedList
     ;;
-  # "do")
-  #   logPrint debug "Command => ${usrCommand}"
-  #   databaseCheckIfExists
-  #   doStart
-  #   ;;
   # "habit")
-  #   logPrint debug "Command => ${usrCommand}"
   #   habitList
   #   ;;
   "decide")
     databaseCheckIfExists
     interactiveDecide
     ;;
+  "event")
+    databaseCheckIfExists
+    eventRouter "${@}"
+    ;;
   "inbox")
     databaseCheckIfExists
-    logPrint debug "Command => ${usrCommand}"
-    shift ; inboxParse "${@}"
+    inboxRouter "${@}"
     ;;
   "review")
     databaseCheckIfExists
@@ -949,19 +1090,16 @@ case ${usrCommand} in
     ;;
   "task")
     databaseCheckIfExists
-    logPrint debug "Command => ${usrCommand}"
-    shift ; taskParse "${@}"
+    taskRouter "${@}"
     ;;
   "work")
     databaseCheckIfExists
     interactiveWork
     ;;
   "--help"|"-h"|"help")
-    logPrint debug "Command => ${usrCommand}"
-    syntaxShow
+    helpShow
     ;;
   "--link")
-    logPrint debug "Command => ${usrCommand}"
     systemLink
     ;;
   *)
