New features: plan task complete & plan completed - Listing data both in ASC and DESC

diff --git a/miniplan/plan b/miniplan/plan
--- a/miniplan/plan
+++ b/miniplan/plan
@@ -35,8 +35,11 @@ fi
 #############
 
 completedList() {
-  echo -e "${colorBold}${colorUnderline}Miniplan - Completed:${colorReset} ${colorDarkGray}(10 last)${colorReset}" ; echo
-  echo -e "$(tail -n 10 ${databaseCompleted})"
+
+  logPrint debug "Completed List"
+
+  databaseTableList completed 100 desc 1 2 3
+
 }
 
 ############
@@ -105,8 +108,7 @@ databaseTableDeleteByString() {
   thisString="${1}" ; shift ; logPrint debug "String => ${thisTable}"
 
   # Deleting
-  sed -i .bkp "1,/${thisString}/{/${thisString}/d;}" "${databasePath}/${thisTable}.db"
-  # sed -i .bkp "/${thisString}/d" "${databasePath}/${thisTable}.db"
+  sed -i .bkp "/${thisString}/d" "${databasePath}/${thisTable}.db"
 
 }
 
@@ -157,7 +159,7 @@ databaseTableInsert() {
 
 databaseTableList() {
 
-  logPrint debug "Database => List"
+  logPrint debug "Database => List $@"
 
   if [ ! "${4}" ]; then
     logPrint error "Missing at least one of the required arguments"
@@ -167,8 +169,22 @@ databaseTableList() {
   # Assigning the user args
   thisTable="${1}"  ; shift ; logPrint debug "Table => ${thisTable}"
   thisLimit="${1}"  ; shift ; logPrint debug "Limit => ${thisLimit}"
-  thisPrefix="${1}" ; shift ; logPrint debug "Prefix => ${thisPrefix}"
+  thisOrder="${1}"  ; shift ; logPrint debug "Order => ${thisOrder}"
   thisKey="${1}"    ; shift ; logPrint debug "Key => ${thisKey}"
+
+  # Validating Order arg
+  case "${thisOrder}" in
+    "asc"|"ASC")
+      thisOrderCommand="head"
+      ;;
+    "desc"|"DESC")
+      thisOrderCommand="tail"
+      ;;
+    *)
+      logPrint error "Wrong value for 'order' argument"
+      exit 1
+      ;;
+  esac
 
   # Header
   echo -e "${colorBold}${colorUnderline}${colorLightGreen}${thisTable^}${colorReset} ${colorDim}(limited to ${thisLimit})${colorReset}"
@@ -176,27 +192,19 @@ databaseTableList() {
 
   # Looping through each entry
   IFS=$'\n'
-  thisRow=1
-  for entry in $(cat "${databasePath}/${thisTable}.db"); do
-
-    if [ ! ${thisRow} -le ${thisLimit} ]; then
-      break
-    fi
+  for entry in $(${thisOrderCommand} -n ${thisLimit} "${databasePath}/${thisTable}.db"); do
 
     # Key
     echo -en "${thisPrefix}${colorBold}`echo "${entry}" | cut -d'|' -f${thisKey}`${colorReset}"
 
     # Additional/optional fields
     unset IFS
-    for field in $1; do
-      echo -n " `echo "${entry}" | cut -d'|' -f$1`"
+    for field in $@; do
+      echo -n " `echo "${entry}" | cut -d'|' -f$field`"
     done
 
     # New line
     echo
-
-    # Iterating this row number
-    ((thisRow++))
 
   done
 
@@ -328,16 +336,23 @@ inboxAdd() {
 
   logPrint debug "Inbox Add"
 
-  if [ ! "${1}" ]; then
+  if [ "${1}" ]; then
+    thisInboxItemName="${@}"  ; logPrint debug "${thisInboxItemName}"
+  else
     logPrint error "Missing inbox item name"
     exit 1
   fi
 
-  thisInboxItemName="${@}"
+  if databaseTableCheckEntryExists inbox "|${thisInboxItemName}$" ; then
+    logPrint error "Inbox item already exists: '${thisInboxItemName}'"
+    exit 1
+  fi
 
-  databaseTableInsert inbox "-" "`timestampGetNow`" "${thisInboxItemName}"
-
-  logPrint info "New item added to Inbox: '${thisInboxItemName}'"
+  if databaseTableInsert inbox "-" "`timestampGetNow`" "${thisInboxItemName}" ; then
+    logPrint info "New inbox item: '${thisInboxItemName}'"
+  else
+    logPrint error "Failed to add inbox item: '${thisInboxItemName}'"
+  fi
 
 }
 
@@ -367,7 +382,7 @@ inboxList() {
 
   logPrint debug "Inbox List"
 
-  databaseTableList inbox 10 "" 1 3
+  databaseTableList inbox 10 asc 1 3
 
 }
 
@@ -742,6 +757,28 @@ taskAdd() {
 
   logPrint debug "Task Add"
 
+  if [ "${1}" ]; then
+    thisTaskName="${@}" ; logPrint debug "${thisTaskName}"
+  else
+    logPrint error "Missing task name"
+    exit 1
+  fi
+
+  if databaseTableCheckEntryExists task "|${thisTaskName}$" ; then
+    logPrint error "Task already exists: '${thisTaskName}'"
+    exit 1
+  fi
+
+  if databaseTableInsert task "[ ]" "`timestampGetNow`" "0" "${thisTaskName}" ; then
+    logPrint info "New task created: '${thisTaskName}'"
+  else
+    logPrint error "Failed to create task: '${thisTaskName}'"
+  fi
+
+}
+
+taskComplete() {
+
   if [ ! "${1}" ]; then
     logPrint error "Missing task name"
     exit 1
@@ -749,11 +786,25 @@ taskAdd() {
 
   thisTaskName="${@}"
 
-  databaseTableInsert task "[ ]" "`timestampGetNow`" "0" "${thisTaskName}"
+  if ! databaseTableCheckEntryExists task "|${thisTaskName}$" ; then
+    logPrint error "Task not found: '${thisTaskName}'"
+    exit 1
+  fi
+  
+  if ! databaseTableInsert completed "[X]" "`timestampGetNow`" "${thisTaskName}" ; then
+    logPrint error "Failed to mark task as completed: '${thisTaskName}'"
+    exit 1
+  fi
 
-  logPrint info "New task created: '${thisTaskName}'"
+  if ! databaseTableDeleteByString task "|${thisTaskName}$" ; then
+    logPring error "Failed to delete task after marking it as completed: '${thisTaskName}'"
+    exit 1
+  fi
+
+  logPrint info "Yay! Another task completed: '${thisTaskName}'"
 
 }
+
 
 taskDelete() {
 
@@ -781,7 +832,7 @@ taskList() {
 
   logPrint debug "Task List"
 
-  databaseTableList task 10 "" 1 4
+  databaseTableList task 10 asc 1 4
 
 }
 
@@ -870,6 +921,11 @@ case ${usrCommand} in
   #   shift
   #   itemAdd "${@}"
   #   ;;
+  "completed")
+    databaseCheckIfExists
+    logPrint debug "Command => ${usrCommand}"
+    completedList
+    ;;
   # "do")
   #   logPrint debug "Command => ${usrCommand}"
   #   databaseCheckIfExists
